### PR TITLE
Fix GitHub Actions deprecation warning

### PR DESCRIPTION
**Pull request by RKrahl**
First of all, many thanks for sharing the doc8 GH action, I use it in some of my projects.  However, the current version of the action triggers a [deprecation warning](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

This PR implements the update instructions to use the `GITHUB_OUTPUT` environment file instead of the deprecated `set-output`.

### CODE REVIEW

**Review by dploeger — APPROVED** [review]
Awesome! Thanks a lot! 🎁

**Comment by dploeger** [comment]
Oh, could you please change the commit message to confirm with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

Basically, you can simply prefix it with "fix:"

Thanks!

**Comment by RKrahl** [comment]
> Oh, could you please change the commit message to confirm with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
> 
> Basically, you can simply prefix it with "fix:"

Done

**Comment by dploeger** [comment]
Currently on mobile. Will release asap

**Comment by dploeger** [comment]
Released as v5

**Pull request merged**
